export { DiffViewer } from './ui/DiffViewer'
export { RunDiff } from './ui/RunDiff'
export { InlineComment } from './ui/InlineComment'
export { useDiffViewerStore } from './model/store'
export type { DiffViewType, DiffViewerState } from './model/store'
export type { ContextGap } from './model/types'
